#!/bin/bash
# This script is used to check the status of the Mavericks slow open osxdaily workaround found at http://osxdaily.com/2013/11/24/slow-open-save-dialog-problem-mac-os-x/
sudo cat /etc/auto_master
