#!/bin/sh
if [ -z "$1" ]
  then
    echo
    echo "must have git repos name ..."
    echo
    exit 1
fi
touch README.md
git init
git add README.md
git commit -m "commit README.md"
git remote add origin https://github.com/mdturnerinoz/$1.git
git push -u origin master